---
# tasks file for apache5
- name: install all the required pacakges
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: start the services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ packages }}"

- name: enable the firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ rules }}"

- name: Copy info file from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
